import type { Metadata } from "next";
import Link from "next/link";
import BreadcrumbSchema from "@/components/BreadcrumbSchema";

export const metadata: Metadata = {
  title: "Date Night Restaurant in Alpharetta, GA | Siena",
  description: "Plan date night in Alpharetta at Siena with Mediterranean and Italian-inspired cuisine, signature cocktails and an elevated atmosphere for dinner for two.",
  alternates: { canonical: "https://sienaatl.com/date-night-alpharetta" },
  openGraph: { title: "Date Night Restaurant in Alpharetta, GA | Siena", description: "Dinner, cocktails and an elevated Mediterranean-inspired setting for date night in Alpharetta.", url: "https://sienaatl.com/date-night-alpharetta" },
};

export default function DateNightPage() {
  return <main className="bg-[#1b312e] text-white"><BreadcrumbSchema trail={[{ name: "Date Night Alpharetta", path: "/date-night-alpharetta" }]} /><section className="mx-auto max-w-5xl px-6 pb-20 pt-36 text-center md:pt-44"><p className="mb-5 text-xs font-semibold uppercase tracking-[0.35em] text-[#e0b265]">Dinner for Two</p><h1 className="text-5xl uppercase leading-none text-[#e0b265] md:text-7xl" style={{ fontFamily: "'Palmore-Light', serif" }}>Date Night Restaurant in Alpharetta</h1><p className="mx-auto mt-8 max-w-3xl text-lg leading-8 text-white/85">Make date night an experience at Siena. Mediterranean-inspired cuisine, Italian influences, cocktails and warm hospitality create an inviting setting for first dates, anniversaries and evenings out together.</p><div className="mt-10"><Link href="/reservations" className="inline-block border border-[#e0b265] px-7 py-3 text-xs font-semibold uppercase tracking-[0.18em] text-[#e0b265]">Reserve Date Night</Link></div></section><section className="bg-[#f4efe5] text-[#1b312e]"><div className="mx-auto grid max-w-6xl gap-12 px-6 py-16 md:grid-cols-2 md:py-24"><div><h2 className="text-4xl uppercase text-[#7d2333] md:text-5xl" style={{ fontFamily: "'Palmore-Light', serif" }}>Dinner &amp; Cocktails</h2><p className="mt-6 leading-8">Start with shareable Mediterranean-inspired plates, explore pasta, seafood and grilled dishes, then pair dinner with a signature cocktail or wine from the bar.</p></div><div><h2 className="text-4xl uppercase text-[#7d2333] md:text-5xl" style={{ fontFamily: "'Palmore-Light', serif" }}>Anniversaries &amp; Celebrations</h2><p className="mt-6 leading-8">For anniversaries and milestone evenings, Siena offers a polished atmosphere without losing the warmth that makes dinner feel personal. Larger celebrations can also explore our private event options.</p></div></div></section><section className="mx-auto max-w-4xl px-6 py-16 text-center md:py-24"><p className="leading-8 text-white/85">Siena is located at 124 Devore Rd in Alpharetta. Explore our <Link href="/mediterranean-restaurant-alpharetta" className="text-[#e0b265] underline">Mediterranean and Italian dining experience</Link> or <Link href="/events" className="text-[#e0b265] underline">plan a private celebration</Link>.</p></section></main>;
}
