import type { Metadata } from "next";
import Link from "next/link";
import BreadcrumbSchema from "@/components/BreadcrumbSchema";

export const metadata: Metadata = {
  title: "Mediterranean Restaurant Near Roswell, GA | Siena",
  description: "Looking for Mediterranean dining near Roswell? Visit Siena in neighboring Alpharetta for Mediterranean and Italian cuisine, cocktails, date nights and celebrations.",
  alternates: { canonical: "https://sienaatl.com/mediterranean-restaurant-near-roswell-ga" },
  openGraph: { title: "Mediterranean Restaurant Near Roswell, GA | Siena", description: "A Mediterranean and Italian dining destination in neighboring Alpharetta for guests from Roswell and North Atlanta.", url: "https://sienaatl.com/mediterranean-restaurant-near-roswell-ga" },
};

export default function RoswellPage() {
  return <main className="bg-[#1b312e] text-white"><BreadcrumbSchema trail={[{ name: "Mediterranean Restaurant Near Roswell", path: "/mediterranean-restaurant-near-roswell-ga" }]} /><section className="mx-auto max-w-5xl px-6 pb-20 pt-36 text-center md:pt-44"><p className="mb-5 text-xs font-semibold uppercase tracking-[0.35em] text-[#e0b265]">Near Roswell, Georgia</p><h1 className="text-5xl uppercase leading-none text-[#e0b265] md:text-7xl" style={{ fontFamily: "'Palmore-Light', serif" }}>Mediterranean Restaurant Near Roswell, GA</h1><p className="mx-auto mt-8 max-w-3xl text-lg leading-8 text-white/85">Searching for an upscale Mediterranean restaurant near Roswell? Siena is located in neighboring Alpharetta and welcomes guests from Roswell and across North Atlanta for Mediterranean-inspired cuisine, Italian influences and signature cocktails.</p><div className="mt-10 flex flex-wrap justify-center gap-4"><Link href="/reservations" className="border border-[#e0b265] px-7 py-3 text-xs font-semibold uppercase tracking-[0.18em] text-[#e0b265]">Reserve a Table</Link><Link href="/menus" className="border border-[#e0b265] px-7 py-3 text-xs font-semibold uppercase tracking-[0.18em] text-[#e0b265]">View Menu</Link></div></section><section className="bg-[#f4efe5] text-[#1b312e]"><div className="mx-auto max-w-5xl px-6 py-16 md:py-24"><h2 className="text-4xl uppercase text-[#7d2333] md:text-5xl" style={{ fontFamily: "'Palmore-Light', serif" }}>Worth the Trip From Roswell</h2><p className="mt-6 max-w-3xl leading-8">Siena offers an elevated setting for date nights, anniversaries, birthday dinners, business dinners, weekend brunch and evenings with friends. Our restaurant is at 124 Devore Rd in Alpharetta, not Roswell, so guests can plan their visit with accurate location information.</p><p className="mt-6 max-w-3xl leading-8">Discover more about <Link href="/mediterranean-restaurant-alpharetta" className="font-semibold underline">Mediterranean dining at Siena in Alpharetta</Link>, explore our <Link href="/menus" className="font-semibold underline">current menus</Link>, or <Link href="/events" className="font-semibold underline">plan a private event</Link>.</p></div></section></main>;
}
